/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mock from "./mock";
export type { mock };
import type * as wTomexSol from "./wTomex.sol";
export type { wTomexSol };
